base_config: config/hilti22/hilti22.yaml

setting:
  data_loader_seq: 'exp05_construction_upper_level_2'

calibration:
  accel_std: 0.0365432018302
  accel_rw: 0.000433
  gyro_std: 0.00367396706572
  gyro_rw: 2.66e-05
  gravity: 9.805