base_config: config/hilti22/hilti22.yaml

setting:
  data_loader_seq: 'exp04_construction_upper_level'

calibration:
  accel_std: 0.1
  accel_rw: 0.0001
  gyro_std: 0.1
  gyro_rw: 0.0001
  gravity: 9.805

tracker:
  source_vox_down_m: 0.1
  iter_n: 100
  GM_grad: 0.1 
  GM_dist: 0.2 

process:
  min_range_m: 0.5
  max_range_m: 50.0
  vox_down_m: 0.06
  min_z_m: -2.0