base_config: config/viral/viral.yaml

setting:
  data_loader_seq: 'spms_01'
  
calibration:
  accel_std: 0.1
  accel_rw: 0.0001
  gyro_std: 0.1
  gyro_rw: 0.0001

process:
  min_range_m: 3.0
  max_range_m: 80.0
  vox_down_m: 0.06
  min_z_m: -3.5