setting:
  name: "test_ncd"
  device: "cuda"
  gpu_id: 0
  use_dataloader: True
  data_loader_name: 'ncd_perturb'
  data_base_dir: '/media/wz/2C96A0A60155E8F8/Dataset/NewerCollege/'
  lidar_topics: 
    master_lidar: '/os1_cloud_node/points'
  camera_topic: '/camera/infra1/image_rect_raw'
  imu_topic: '/os1_cloud_node/imu'
  output_root: "./experiments/ncd_perturb/"
calibration:
  gravity: 9.781
  accel_std: 0.001249
  accel_rw: 0.000106
  gyro_std: 0.000208
  gyro_rw: 0.000004
  T_imu_lidar: [-1.0,  0.0,  0.0,  -0.006253,
                0.0,  -1.0,  0.0,  0.011775,
                0.0,  0.0,  1.0,  -0.028535,
                0.0,  0.0,  0.0,  1.0] #os_lidar->os_imu
  T_imu_camera: [ 0.70992163,  0.02460003,  0.70385092,  0.04249269,
           -0.70414167,  0.00493623,  0.71004236,  0.06466842,
           0.01399269, -0.99968519,  0.02082624, -0.01845775,
           0.00000000,  0.00000000,  0.00000000,  1.00000000 ]
  fx: 353.83530850045827
  fy: 353.08084839605925
  cx: 354.9603638484091
  cy: 261.96623968254306
  width: 720
  height: 540
  distorted: True
  k1: -0.03908623683636908
  k2: -0.008364734078508202
  p1: 0.006865315014140142
  p2: -0.0022325156415695015
  timeshift: -0.0618701993111 #(t_imu = t_cam + shift)
process:
  min_range_m: 1.5
  max_range_m: 80.0
  min_z_m: -5.0
  vox_down_m: 0.08
  adaptive_range_on: False
sampler:
  surface_sample_range_m: 0.25 
  surface_sample_n: 4
  free_sample_begin_ratio: 0.3
  free_sample_end_dist_m: 1.0
  free_front_sample_n: 2
neuralpoints:
  voxel_size_m: 0.4
  feature_dim: 8 
  query_nn_k: 6
  search_alpha: 0.2
  weighted_first: False
loss:
  sigma_sigmoid_m: 0.1
  loss_weight_on: True
  dist_weight_scale: 1.0
  ekional_loss_on: True
  weight_e: 0.5
continual:
  batch_size_new_sample: 1000
  pool_capacity: 2e7
tracker:
  source_vox_down_m: 0.8
  iter_n: 100
  valid_nn_k: 5
pgo:
  map_context: True
  context_cosdist: 0.25
  pgo_freq_frame: 30
optimizer: # mapper
  iters: 30
  batch_size: 16384      
eval:
  o3d_vis_on: False # visualize the mapping or not
  silence_log: True # output the logs or not
  sensor_cad_path: ''
  mesh_freq_frame: 1000 # reconstruct the mesh every x frames
  mesh_min_nn: 9
  save_mesh: True
  save_map: False
  save_merged_pc: False
  log_freq_frame: 1000