base_config: config/hilti21/hilti21.yaml

setting:
  data_loader_seq: 'Construction_Site_2'

process:
  min_range_m: 2.0
  max_range_m: 150.0
  vox_down_m: 0.08
  min_z_m: -3.5

calibration:
  accel_std: 0.1
  accel_rw: 0.0001
  gyro_std: 0.1
  gyro_rw: 0.0001