base_config: config/hilti21/hilti21.yaml

setting:
  data_loader_seq: 'uzh_tracking_area_run2'

process:
  min_range_m: 1.5
  max_range_m: 30.0
  vox_down_m: 0.06
  min_z_m: -2.

calibration:
  accel_std: 0.1
  accel_rw: 0.0001
  gyro_std: 0.1
  gyro_rw: 0.0001